### ISSUE TITLE
在pubilc下没有发现install      url/install安装是怎么实现的啊

### ISSUE THREAD

**Issue by houyushan** [hiliqi/xiaohuanxiong#17]
在pubilc下没有发现install      url/install安装是怎么实现的啊

按大神文档步骤到安装 url/install 这一步报无此文件

**Comment by hiliqi** [comment]
请加QQ群提问




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"houyushan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月26日(星期天) 凌晨1:07
收件人:&nbsp;"hiliqi/xiaohuanxiong"<xiaohuanxiong@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[hiliqi/xiaohuanxiong] 在pubilc下没有发现install      url/install安装是怎么实现的啊 (#17)





 
在pubilc下没有发现install      url/install安装是怎么实现的啊
 
按大神文档步骤到安装 url/install 这一步报无此文件
